### ISSUE TITLE
[BUG] 'Search - Browse All' not showing results

### ISSUE THREAD

**Issue by RookiNumbers** [doggybootsy/Dribbblish#2]
While having Dribbblish enabled, When navigating to 'Search', and then clicking anything listed under 'Browse All', it shows my home page, but with the title replaced. 
I can't actually access any charts because of this.

Homepage:
![Schermafbeelding 2021-08-27 131647](https://user-images.githubusercontent.com/75414815/131119647-89f00491-050b-40aa-bc6b-5cdb75e148fa.png)

Search:
![Schermafbeelding 2021-08-27 131717](https://user-images.githubusercontent.com/75414815/131119652-52a14e89-84ac-4fd1-8483-a83144661ce0.png)

After clicking 'New Releases':
![Schermafbeelding 2021-08-27 131615](https://user-images.githubusercontent.com/75414815/131119654-34be663f-5b13-476e-a75e-3b0b8dad6aa7.png)

**Comment by doggybootsy** [comment]
Use the proper repo, this is the discord version I made not the spicetify one

**Comment by frolleks** [comment]
this is so funny
